# @package _global_

terrain:
  _target_: motion_tracking.envs.terrains.terrain.Terrain
  terrain_config:
    static_friction: 1.0  # [-]
    dynamic_friction: 1.0  # [-]
    restitution: 0.        # [-]
    # rough terrain only:
    terrain_composition: ${terrain_composition}
    max_init_map_level: 0
    # easiest if it's a square.
    map_length: 20.
    map_width: 20.
    border_size: 20.  # ensure sufficient space from the edges
    num_levels: 10
    num_terrains: 10
    # terrain types: [smooth slope, rough slope, stairs up, stairs down, discrete, stepping, poles, flat]
  #  terrain_proportions: [ 0.2, 0.1, 0.15, 0.15, 0.05, 0., 0.25, 0.1 ]
    terrain_proportions: [ 0.2, 0.1, 0.15, 0.15, 0.05, 0., 0., 0.35 ]
    # tri mesh only:
    slope_threshold: 0.9
    velocity_map: False
    num_samples: 16 #64
    sample_width: 1
    horizontal_scale: 0.1
    vertical_scale: 0.005
    max_num_objects: ${max_num_objects}
    spacing_between_objects: 5
    terrain_path: ${terrain_path}
    load_terrain: ${load_terrain}
    save_terrain: ${save_terrain}


terrain_model:
  _target_: motion_tracking.agents.models.common.Flatten
  config:
    normalize_obs: False
    obs_clamp_value: ${obs_clamp_value}
  num_in: ${eval:${terrain.terrain_config.num_samples}**2}
  num_out: ${eval:${terrain.terrain_config.num_samples}**2}


mu_model:
  config:
    extra_inputs:
      terrain: ${terrain_model}


critic:
  config:
    extra_inputs:
      terrain: ${terrain_model}

algo_extra_inputs:
  terrain:
    retrieve_from_env: True
    dtype: float
    size: ${eval:${terrain.terrain_config.num_samples}**2}
    env_obs_name: terrain_obs

terrain_composition: curriculum
terrain_path: null
load_terrain: False
save_terrain: False
