# @package _global_

trainer:
  logger:
    - _target_: pytorch_lightning.loggers.TensorBoardLogger
      save_dir: ${save_dir}
    - _target_: pytorch_lightning.loggers.WandbLogger
      name: ${name}
      save_dir: ${save_dir}
      project: ${wandb_project}
      tags: ${wandb_tags}
      group: ${wandb_group}
      id: ${wandb_id}
      entity: ${wandb_entity}

wandb_project: physical_animation
wandb_tags: [ "${version}" ]
wandb_group: null
wandb_id: null
wandb_entity: null
